data:
  file_path: "/eos/cms/store/group/dpg_bril/comm_bril/2025/physics/"
  beam_path: "/eos/cms/store/group/dpg_bril/comm_bril/2025/physics/"
  node: "hfetlumi"
  fills: [10855]

pipeline:
  revert_online:
    enable: true
    afterglow_node: "hfafterglowfrac"
    pedestal_node:  "hfEtPedestal"
  batch_afterglow_lsq:
    enable: false
    hfsbr_file: "afterglow/hfet25lsq.txt"
    lambda_reg: 0.01
    lambda_nonactive: 0.05
    lambda_bx1: 1.0
    use_cubic: true
    n_jobs: -1
    backend: "processes"   # "processes" | "threads"
    p0_guess: [0.02116, 0.02141, 0.02053, 0.02055]

sbr:
  enable: false

plot:
  per_bx: true
  instant: true

io:
  save_hd5: false
  out_dir: "./out/"

